services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatapp
      MYSQL_PASSWORD: chatapp
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
